### PR TITLE
Added test coverage and remove the temporary files for remote disks

### PR DESCRIPTION
**Pull request by lunfel**
I added a test coverage for the package. It's 100% code coverage right now! Yay
I added tests for remote disks which is optional that uses docker-compose to emulate remote disk.
I added the documentation for the tests and remote disk tests to the README file
A local disk and a remote disk are now used in the same way as they implement the same contract. This leads to the temporary files not being needed anymore. All code related to temporary files and clean up is removed
The dependencies have been upgraded to work at least with Laravel 7. Should work with Laravel 6 but I haven't tested.

### CODE REVIEW

**Comment by ymslavov** [comment]
@lunfel thank you so much for the effort you put in this! This has somehow slipped through the cracks and I'm noticing it just now. As there were other changes to the files, your changes are now clashing, can I please ask you to get your branch up to date with master so I can merge this as well? It will be much appreciated.

Again, thanks a lot for your support!
Yasen

**Comment by lunfel** [comment]
I will gladly look into this in the next few days when I will be able to.

**Comment by lunfel** [comment]
Conflicts has been merged!

**Comment by ymslavov** [comment]
@lunfel thanks again for the support I will be pushing a new package release version today :+1:

**Pull request merged**
